// 실제 CDN 이미지 URL이 포함된 게임 데이터 (데모용)
// CDN: https://fan-cdn.nolimitcity.com/

export const DEMO_GAMES = [
  // === Nolimit City ===
  {
    id: 'catfish-hunters',
    name: 'Catfish Hunters',
    provider: 'Nolimit City',
    category: 'slots',
    thumbnail: 'https://fan-cdn.nolimitcity.com/small_Website_Icon_Catfish_Hunters_47ef66edfe.jpg',
    maxWin: 'x10000',
    rtp: 96.09,
    isHot: true,
    isNew: true,
  },
  {
    id: 'fire-in-the-hole',
    name: 'Fire in the Hole',
    provider: 'Nolimit City',
    category: 'slots',
    thumbnail: 'https://fan-cdn.nolimitcity.com/small_Website_Icon_Fire_in_the_Hole_6a7e59f2c5.jpg',
    maxWin: 'x60000',
    rtp: 96.06,
    isHot: true,
    isNew: false,
  },
  {
    id: 'fire-in-the-hole-3',
    name: 'Fire in the Hole 3',
    provider: 'Nolimit City',
    category: 'slots',
    thumbnail: 'https://fan-cdn.nolimitcity.com/small_Website_Icon_Fire_in_the_Hole_3_3c1fa8e3d2.jpg',
    maxWin: 'x55000',
    rtp: 96.02,
    isHot: true,
    isNew: true,
  },
  {
    id: 'punk-rocker-2',
    name: 'Punk Rocker 2',
    provider: 'Nolimit City',
    category: 'slots',
    thumbnail: 'https://fan-cdn.nolimitcity.com/small_Website_Icon_Punk_Rocker_2_8b3d1f4e7a.jpg',
    maxWin: 'x35000',
    rtp: 96.04,
    isHot: false,
    isNew: true,
  },
  {
    id: 'dead-or-alive-2',
    name: 'Dead or Alive 2',
    provider: 'Nolimit City',
    category: 'slots',
    thumbnail: 'https://fan-cdn.nolimitcity.com/small_Website_Icon_Dead_or_Alive_2_Feature_Buy_9c2e4a1b3d.jpg',
    maxWin: 'x111111',
    rtp: 96.80,
    isHot: true,
    isNew: false,
  },
  {
    id: 'brute-force',
    name: 'Brute Force: Alien Onslaught',
    provider: 'Nolimit City',
    category: 'slots',
    thumbnail: 'https://fan-cdn.nolimitcity.com/small_Website_Icon_Brute_Force_Alien_Onslaught_4d5e6f7a8b.jpg',
    maxWin: 'x25000',
    rtp: 96.01,
    isHot: false,
    isNew: true,
  },
  {
    id: 'sugar-crush',
    name: 'Sugar Crush',
    provider: 'Nolimit City',
    category: 'slots',
    thumbnail: 'https://fan-cdn.nolimitcity.com/small_Website_Icon_Sugar_Crush_2a3b4c5d6e.jpg',
    maxWin: 'x15000',
    rtp: 96.05,
    isHot: false,
    isNew: false,
  },
  {
    id: 'kill-em-all',
    name: 'Kill Em All',
    provider: 'Nolimit City',
    category: 'slots',
    thumbnail: 'https://fan-cdn.nolimitcity.com/small_Website_Icon_Kill_Em_All_7f8g9h0i1j.jpg',
    maxWin: 'x30000',
    rtp: 96.03,
    isHot: false,
    isNew: false,
  },

  // === NetEnt ===
  {
    id: 'godbreaker',
    name: 'Godbreaker',
    provider: 'NetEnt',
    category: 'slots',
    thumbnail: 'https://fan-cdn.nolimitcity.com/small_godbreaker_playin_ne_logo_thumbnail_512x512_722ee1add1.png',
    maxWin: 'x10000',
    rtp: 96.10,
    isHot: true,
    isNew: true,
  },
  {
    id: 'gonzos-quest-2',
    name: "Gonzo's Quest II",
    provider: 'NetEnt',
    category: 'slots',
    thumbnail: 'https://fan-cdn.nolimitcity.com/small_gonzos_quest_2_playin_ne_logo_thumbnail_512x512_3a4b5c6d7e.png',
    maxWin: 'x15000',
    rtp: 96.20,
    isHot: true,
    isNew: false,
  },
  {
    id: 'dead-west',
    name: 'Dead West',
    provider: 'NetEnt',
    category: 'slots',
    thumbnail: 'https://fan-cdn.nolimitcity.com/small_dead_west_playin_ne_logo_thumbnail_512x512_1b2c3d4e5f.png',
    maxWin: 'x8000',
    rtp: 96.15,
    isHot: false,
    isNew: true,
  },
  {
    id: 'piggy-riches-3',
    name: 'Piggy Riches 3',
    provider: 'NetEnt',
    category: 'slots',
    thumbnail: 'https://fan-cdn.nolimitcity.com/small_piggy_riches_3_playin_ne_logo_thumbnail_512x512_6g7h8i9j0k.png',
    maxWin: 'x5000',
    rtp: 96.30,
    isHot: false,
    isNew: false,
  },

  // === Red Tiger ===
  {
    id: 'monopoly-money-line',
    name: 'MONOPOLY Money Line',
    provider: 'Red Tiger',
    category: 'slots',
    thumbnail: 'https://fan-cdn.nolimitcity.com/small_monopoly_money_line_playin_rt_logo_thumbnail_512x512_a1b2c3d4e5.png',
    maxWin: 'x10000',
    rtp: 95.70,
    isHot: true,
    isNew: true,
  },
  {
    id: 'monopoly-money-magnate',
    name: 'MONOPOLY Money Magnate',
    provider: 'Red Tiger',
    category: 'slots',
    thumbnail: 'https://fan-cdn.nolimitcity.com/small_monopoly_money_magnate_playin_rt_logo_thumbnail_512x512_2075ed6aa8.png',
    maxWin: 'x8000',
    rtp: 95.80,
    isHot: false,
    isNew: false,
  },

  // === Big Time Gaming ===
  {
    id: 'bonanza',
    name: 'Bonanza Megaways',
    provider: 'Big Time Gaming',
    category: 'slots',
    thumbnail: 'https://fan-cdn.nolimitcity.com/small_BTG_Bonanza_Icon_689d061954.png',
    maxWin: 'x12000',
    rtp: 96.00,
    isHot: true,
    isNew: false,
  },
  {
    id: 'monopoly-deluxe',
    name: 'Monopoly Deluxe',
    provider: 'Big Time Gaming',
    category: 'slots',
    thumbnail: 'https://fan-cdn.nolimitcity.com/small_BTG_Monopoly_Deluxe_Icon_5f6g7h8i9j.png',
    maxWin: 'x20000',
    rtp: 96.50,
    isHot: false,
    isNew: true,
  },
];

// 프로바이더 목록
export const PROVIDERS = [
  { name: 'Nolimit City', slug: 'nolimit', gameCount: 8, color: '#E8593C' },
  { name: 'NetEnt', slug: 'netent', gameCount: 4, color: '#00C853' },
  { name: 'Red Tiger', slug: 'redtiger', gameCount: 2, color: '#FF6D00' },
  { name: 'Big Time Gaming', slug: 'btg', gameCount: 2, color: '#D4AF37' },
];

// 카테고리 목록
export const CATEGORIES = [
  { name: '전체', slug: 'all', icon: '🎮', count: 16 },
  { name: '인기', slug: 'hot', icon: '🔥', count: 7 },
  { name: '신규', slug: 'new', icon: '⭐', count: 7 },
  { name: '슬롯', slug: 'slots', icon: '🎰', count: 16 },
  { name: '라이브', slug: 'live', icon: '🎲', count: 0 },
  { name: '테이블', slug: 'table', icon: '♠️', count: 0 },
];
